# Generated by Django 2.2.16 on 2022-06-25 09:27

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220624_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.validate_year], verbose_name='Year of issue'),
        ),
    ]
